# Site settings

title: Open Source Mirror
school: ""
brand: Open Source Mirror
operator: ""
author: Mirror Operator
desc: 开源软件镜像与同步状态。
baseurl: ""
permalink: "/:categories/:title/"
url: "https://mirrors.example.com"
hostname: "mirrors.example.com"
urlv4: false
urlv6: false
aosp: "mirrors.example.com"
arch_archive: "mirrors.example.com"
pypi: "mirrors.example.com"
homelink: "/"
hide_navbar: true
hide_download: false
hide_server_status: false

hide_mirrorz: false
mirrorz_desc: 校园网联合镜像站
mirrorz_link: "https://mirrors.cernet.edu.cn/list"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

# ==================================
# Build settings below, DO NOT TOUCH
# ==================================

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

vite:
    config_path: _src/vite.json
    viteConfig: _vite.config.mjs

plugins:
    - jekyll-relative-links
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

jekyll-minifier:
    exclude: [ 'assets/*' ]

exclude: [gen_robot.sh, geninfo/, gen_desc.py]
addition_exclude:
    - package.json
    - package-lock.json
    - node_modules/
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor/
    - Dockerfile*
    - LICENSE

helpz:
    language: zh
    collection:
        label: help

defaults:
  - scope:
      path: ""
      type: "help"
    values:
      layout: "help"
      excerpt_separator: ""

# vim: ts=2 sts=2 sw=2 expandtab
